### ISSUE TITLE
Inkplate 5 Hardware Repo

### ISSUE THREAD

**Issue by Dianoga** [SolderedElectronics/Inkplate-documentation#13]
Is the hardware repo for the Inkplate 5 still coming soon? I'd like to see how it differs from the other displays to see if it can be made to work with ESPHome

**Comment by rsoric** [comment]
Hi @Dianoga 

it should be up soon but in the meantime please write to us on [customer support](https://soldered.com/hr/contact/), I'll send you the files there. But to also answer your question, ESPHome should work fine with a slightly modified driver from the existing ones.

-Rob
