### ISSUE TITLE
Inkplate 5 hardware repository is coming soon

### ISSUE THREAD

**Issue by gmacario** [SolderedElectronics/Inkplate-documentation#14]
From https://inkplate.readthedocs.io/en/latest/hardware-reference.html

> Inkplate 5 hardware repository is coming soon

Do you have a better definition of "soon"?

I am particularly interested in the mechanical specification of the Inkplate 5 PCB in order to design a 3D-printable enclosure.

As a workaround, one or more suitable STL could work out, too :wink:

**Comment by rsoric** [comment]
Hi Gianpaolo,

unforunately we're not sure on an ETA for the repository, but I'm happy to share the current version of the .stl files here: 
[inkplate5_3d_case.zip](https://github.com/SolderedElectronics/Inkplate-documentation/files/13809505/inkplate5_3d_case.zip)

**Comment by gmacario** [comment]
Thank you for the .STL @rsoric, I will try and print the enclosure next week when I am back in the office.

Concerning the hardware repository for the Inkplate 5 If there is anything I can do to help you with setting it up please let me know. As you probably know I own one board which I sourced from CrowdSupply a couple of month ago and I am interested in using this nice PCB for an open source project I am currently working on.

**Comment by rsoric** [comment]
@ifadiga can we get an ETA on this?

**Comment by ifadiga** [comment]
Hello,

We don't know when the Inkplate 5 hardware repository will be published. We working on some things to set up automation.

Here are the CAD files for Inkplate, I hope that will help you until we publish all files in the repository.
[Soldered Inkplate 5 HW.zip](https://github.com/SolderedElectronics/Inkplate-documentation/files/13816510/Soldered.Inkplate.5.HW.zip)
